# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd638243ba13b728e9479e51fd3a045689f98be472cded3381c46bdb9fb12a4786d931ccf2c3453d34a3192050a6ddd9b845f1e4f89c813f32be360fcc422e32

test:
  secret_key_base: 53f2e6205c2471547fec822a0d540cd9ece578eb571b4ec1e491cd0af32d8a872683ae4ff1c7c7c860306b29dc3735ef0367c7a26f900ea12407e3f534470936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
